# Generated by Django 4.2.2 on 2023-06-19 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('empresa', models.CharField(max_length=110)),
                ('ombro', models.IntegerField()),
                ('torax_busto', models.IntegerField()),
                ('cintura_alta', models.IntegerField()),
                ('cintura_baixa', models.IntegerField()),
                ('quadril', models.IntegerField()),
                ('altura_corpo', models.IntegerField()),
                ('comp_camisa_ete', models.IntegerField()),
                ('comp_blazer', models.IntegerField()),
                ('comp_vestido', models.IntegerField()),
                ('comp_manga_curta', models.IntegerField()),
                ('comp_manga_longa', models.IntegerField()),
                ('larg_braco', models.IntegerField()),
                ('punho', models.IntegerField()),
                ('larg_perna', models.IntegerField()),
                ('comp_saia', models.IntegerField()),
                ('comp_calca', models.IntegerField()),
            ],
        ),
    ]
