# Generated by Django 4.2.2 on 2023-06-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='comp_camisa_ete',
            new_name='comp_camisa',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='ombro',
            new_name='ombro_ombro',
        ),
    ]
