# Generated by Django 4.2.2 on 2023-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0002_rename_comp_camisa_ete_pessoa_comp_camisa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=100)),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
