# Generated by Django 4.2.2 on 2023-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0003_tecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('cliente', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
