# Generated by Django 4.2.2 on 2023-09-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0005_pessoa_tamanho_blazer_pessoa_tamanho_blusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
